"""
One-off cleanup: consolidate the user's hand-cleaned hustings events
(folders `sthelier-connetable-2026/`, `sthelier-north-deputy-2026/` —
which use a non-canonical slug shape) into the canonical-slug folders
the auto-generator produced (`st-helier-connetable-2026/`,
`st-helier-north-deputy-2026/`).

For each pair:
  1. Copy hand-cleaned transcript.md over the auto folder's transcript.md.
  2. Merge metadata.yaml — keep auto's roster, copy moderator_names +
     event_date from the user's hand version.
  3. Drop the old DB row (CASCADE wipes its segments + topic tags).
  4. Delete the old folder.

After this the next `ingest_hustings.py` run with the new slug picks up
the hand-cleaned transcript and re-creates the DB rows under the
canonical slug, and `classify_hustings.py` re-tags the segments.

Run once:
  python pipeline/consolidate_slug_collisions.py
"""

from __future__ import annotations

import os
import shutil
import sys
from pathlib import Path

import psycopg2
import yaml
from dotenv import load_dotenv

load_dotenv(override=True)

HUSTINGS = Path(__file__).resolve().parent / 'hustings'

# Old slug → canonical slug. Both folders must exist (the canonical one
# was auto-generated by hustings_metadata_from_youtube.py).
PAIRS = [
    ('sthelier-connetable-2026', 'st-helier-connetable-2026'),
    ('sthelier-north-deputy-2026', 'st-helier-north-deputy-2026'),
]

# Also clean up the auto sandbox folder used during the original audio
# pipeline smoke test — its outputs (audio.wav, words.json, etc.) are
# no longer needed.
SANDBOX_FOLDERS = [
    'sthelier-connetable-2026-auto',
]


def main():
    conn = psycopg2.connect(os.environ['DATABASE_URL'])
    cur = conn.cursor()
    try:
        for old_slug, new_slug in PAIRS:
            old = HUSTINGS / old_slug
            new = HUSTINGS / new_slug
            print(f'\n=== {old_slug} → {new_slug} ===')

            if not old.exists():
                print(f'  no old folder, skipping')
                continue
            if not new.exists():
                print(f'  no new folder, skipping (run metadata_from_youtube first)')
                continue

            # 1. Copy hand-cleaned transcript.md
            old_transcript = old / 'transcript.md'
            if old_transcript.exists():
                shutil.copy2(old_transcript, new / 'transcript.md')
                print(f'  copied transcript.md ({old_transcript.stat().st_size} bytes)')

            # 2. Merge metadata.yaml
            old_meta = yaml.safe_load((old / 'metadata.yaml').read_text()) or {}
            new_meta = yaml.safe_load((new / 'metadata.yaml').read_text()) or {}
            new_meta['moderator_names'] = old_meta.get('moderator_names') or []
            if not new_meta.get('event_date') and old_meta.get('event_date'):
                new_meta['event_date'] = old_meta['event_date']
            if not new_meta.get('youtube_url') and old_meta.get('youtube_url'):
                new_meta['youtube_url'] = old_meta['youtube_url']
            (new / 'metadata.yaml').write_text(
                yaml.safe_dump(new_meta, sort_keys=False, allow_unicode=True),
                encoding='utf-8',
            )
            print(f'  merged metadata.yaml '
                  f'(moderator_names={new_meta["moderator_names"]}, '
                  f'event_date={new_meta.get("event_date")})')

            # 3. Drop the old DB row — CASCADE wipes segments + topic tags
            cur.execute('DELETE FROM hustings_events WHERE slug = %s', (old_slug,))
            print(f'  deleted DB row for {old_slug} ({cur.rowcount} row affected)')
            conn.commit()

            # 4. Delete the old folder
            shutil.rmtree(old)
            print(f'  removed {old}')

        # 5. Clean up the sandbox folder used for the audio-pipeline smoke test.
        for sb in SANDBOX_FOLDERS:
            p = HUSTINGS / sb
            if p.exists():
                shutil.rmtree(p)
                print(f'\nremoved sandbox folder: {p}')

    finally:
        cur.close()
        conn.close()

    print('\nDone. Next: run ingest_hustings + classify_hustings for the new slugs.')


if __name__ == '__main__':
    main()
