/**
 * TranscriptMethodBadge — small inline badge that tells the reader how a
 * given hustings transcript was produced.
 *
 *   hand_cleaned             — emerald, "Hand-cleaned"
 *   auto_pipeline_reviewed   — sky, "Reviewed"
 *   auto_pipeline            — amber, "Auto-transcribed"
 *
 * The amber colour is deliberate: it signals to the reader that they
 * should expect occasional STT artefacts (dropped pronouns, mis-
 * attributed speakers, audience members shown as <SPEAKER_NN>). The
 * reviewer pass moves an event from auto_pipeline → auto_pipeline_reviewed
 * via the metadata.yaml `speaker_overrides:` mechanism + manual checks.
 *
 * Used on:
 *   * /hustings index event cards
 *   * /hustings/[event] header
 *   * Candidate profile "Hustings appearances" event header
 *   * /hustings/topics/[topic] event grouping
 */

type Method = "hand_cleaned" | "auto_pipeline" | "auto_pipeline_reviewed";

const STYLES: Record<Method, { bg: string; text: string; label: string; title: string }> = {
  hand_cleaned: {
    bg: "bg-emerald-50 dark:bg-emerald-900/30 border-emerald-200 dark:border-emerald-800",
    text: "text-emerald-700 dark:text-emerald-300",
    label: "Hand-cleaned",
    title:
      "Transcribed and attributed by a human reviewer. Every word is verbatim and every speaker is correctly identified.",
  },
  auto_pipeline_reviewed: {
    bg: "bg-sky-50 dark:bg-sky-900/30 border-sky-200 dark:border-sky-800",
    text: "text-sky-700 dark:text-sky-300",
    label: "Reviewed",
    title:
      "Generated by the audio pipeline and reviewed by a human — speaker mis-attributions corrected via speaker_overrides.",
  },
  auto_pipeline: {
    bg: "bg-amber-50 dark:bg-amber-900/30 border-amber-200 dark:border-amber-800",
    text: "text-amber-700 dark:text-amber-300",
    label: "Auto-transcribed",
    title:
      "Generated by yt-dlp + Whisper + pyannote. Expect occasional STT artefacts (dropped 'I' pronouns, mis-attributed speakers, audience speakers shown as <SPEAKER_NN>). Watch the YouTube source for ground truth.",
  },
};

export function TranscriptMethodBadge({
  method,
  size = "sm",
}: {
  method: Method;
  size?: "sm" | "xs";
}) {
  const s = STYLES[method] ?? STYLES.auto_pipeline;
  const pad = size === "xs" ? "px-1.5 py-0.5 text-[10px]" : "px-2 py-0.5 text-xs";
  return (
    <span
      title={s.title}
      className={`inline-flex items-center font-medium whitespace-nowrap rounded border ${s.bg} ${s.text} ${pad}`}
    >
      {s.label}
    </span>
  );
}

export type TranscriptMethod = Method;
